---
- name: Deploy Docker Image to Container
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Pull Docker Image
      docker_image:
        name: "{{user}}/{{image}}:{{tag}}"
        source: pull

    - name: Create & Start Calculator Docker Container
      docker_container:
        name: calculator-using-devops
        image: "{{user}}/{{image}}:{{tag}}"
        state: started
        tty: yes
        interactive: yes

